V1_CONFIG_FILE = "config.yaml"
V2_CONFIG_FILE = "tauticord.yaml"
MIGRATION_001_CONFIG_FILE = "001_env_var_to_config_yaml.yaml"
MIGRATION_002_CONFIG_FILE = "002_old_config_to_new_config.yaml"
MIGRATION_003_CONFIG_FILE = "m003_add_recently_added_webhook.yaml"
MIGRATION_004_CONFIG_FILE = "m004_split_text_channel_names.yaml"
